### ISSUE TITLE
Fresh template install returns 404 for serve

### ISSUE THREAD

**Issue by rolandleth** [netlify/remix-template#132]
**Describe the bug**
Fresh install returns 404 Not Found for serve.

**To Reproduce**
1. Run `npx create-remix@latest --template netlify/remix-template`
2. Select Netlify Functions option when prompted
3. `cd` into the newly-created app directory
4. Run `npm run start`
5. Observe 404 Not Found

**Expected behavior**
To have the same content load as `nom run dev`.

**Screenshots**
<img width="1275" alt="1" src="https://github.com/netlify/remix-template/assets/1858700/181aa325-f19c-41b6-9616-69fb928d13c3">

`npm run start`:

<img width="563" alt="2" src="https://github.com/netlify/remix-template/assets/1858700/a3a508df-7005-40d0-8dbb-6aca29948a84">

**Desktop (please complete the following information):**
 - OS: macOS 14.1.1
 - Browser Safari or Chrome

Am I doing something wrong? Shouldn't it work locally as well? `nom run dev` works properly.

**Comment by anthonyholmes** [comment]
netlify-cli@17.9 works correctly

**Comment by th-km** [comment]
After deploying the template I'm also getting 404 on ressources (manifest, entry.client...). See [here](https://remix-ntl.netlify.app/) and have a look at the network tab.

**Comment by ascorbic** [comment]
Fixed in latest version

**Comment by rolandleth** [comment]
@ascorbic hello! I'm still facing this issue, am I doing something wrong? Using `netlify-cli@17.19.3`.

<img width="675" alt="Screenshot 2024-03-14 at 7 10 04 PM" src="https://github.com/netlify/remix-template/assets/1858700/bc0c3e1a-67f2-4634-944b-201906c55d2c">
