### ISSUE TITLE
Fresh install returns 404 error for run dev

### ISSUE THREAD

**Issue by gregdingle** [netlify/remix-template#134]
**Describe the bug**
After doing a fresh install with edge functions, `npm run dev` starts a server on http://localhost:8888 but that address returns 404. 

**To Reproduce**
See screenshots below

**Expected behavior**
Expected to see remix index page.

**Screenshots**
![CleanShot 2023-12-18 at 00 21 10](https://github.com/netlify/remix-template/assets/28797/bfa2ac4c-83f2-4695-94cd-d1bc3582f25d)

![CleanShot 2023-12-18 at 00 22 50](https://github.com/netlify/remix-template/assets/28797/834f4d9b-3ab9-4672-8c7c-0d557990085f)

![CleanShot 2023-12-18 at 00 25 34](https://github.com/netlify/remix-template/assets/28797/3f1040f1-6285-48f8-8285-e0331ad62f15)

**Comment by anthonyholmes** [comment]
netlify-cli@17.9 works correctly. You might need to downgrade for now

**Comment by anthonyholmes** [comment]
Actually, it starts working correctly if you save one of your project files. You might need to refresh the browser too. Definitely started happening after netlify-cli@17.9 though

**Comment by yuvrajharod** [comment]
Thanks @anthonyholmes , this really helped a lot! I was facing the same issue and this worked me!

**Comment by sangrepura** [comment]
Just tried this today as well since I was considering Netlify over Fly.io.  Got a 404 on fresh installs of this template and the `netlify-cli`  (`v17.15.2`).  Adding a newline to `root.tsx` and saving as  @anthonyholmes suggested fixed it.  
But this is not a good first impression for new people coming to your platform @Netlify.

**Comment by ascorbic** [comment]
Thanks for the report on this, and sorry for the delay in addressing it. We're looking into it.

FRA-237

**Comment by sangrepura** [comment]
Thanks for looking into this!  Some additional behavior I noticed:

1.  Every time the dev server is started with: `remix dev --manual -c \"ntl dev --framework=#static\"`
    a file needs to be edited and saved while it's running  to eliminate the 404
2.  HMR doesn't work (auto reload the page) on the initial edit/save while the 404 is displayed, but it does work on subsequent edits.

**Comment by ascorbic** [comment]
This is updated in the build library. I'll update here when we have a CLI update. It should be later today.

**Comment by ascorbic** [comment]
@sangrepura I think that may be the same issue

**Comment by ascorbic** [comment]
Everyone here: if you update `netlify-cli` to latest (which is now `17.15.5`) it should fix this for you. Thanks everyone for your patience on this.

**Comment by anthonyholmes** [comment]
I'm still having the issue after upgrading. Any suggestions on how I can help debug this?

**Comment by yuvrajharod** [comment]
@ascorbic tried after upgrading, I can confirm, this isn't fixed yet. 

Can you please confirm if we need to upgrade anything else?

**Comment by ascorbic** [comment]
Looking into this. Thanks for the reports.

**Comment by th-km** [comment]
I'm experiencing the same issue with `netlify-cli: "^17.16.3"`. I'm also curious to know if there are plans for a vite preset?
